### ISSUE TITLE
Async method pains again

### ISSUE THREAD

**Issue by gaspoweredkiwi** [gaspoweredkiwi/tab-tracker#1]
## Potential fixes to try:
- [x] Reinstall node/npm
- [ ] Delete and reinstall node_modules
*More to be added as I discover them*
--------------------
## Details
**Node version:** 8.6.0
**NPM version:** 5.5.1
**Global packages:**
```
npm ls -g --depth=0
/home/chris_l/.nvm/versions/node/v8.6.0/lib
├── npm@5.5.1
├── sass-lint@1.12.0
└── vue-cli@2.9.1
```
**Local packages:**
```
npm ls --depth=0
server@1.0.0 /home/chris_l/dev/tab-tracker/server
├── body-parser@1.18.2
├── cors@2.8.4
├── eslint@4.8.0
├── eslint-config-standard@10.2.1
├── eslint-plugin-import@2.7.0
├── eslint-plugin-node@5.2.0
├── eslint-plugin-promise@3.6.0
├── eslint-plugin-standard@3.0.1
├── express@4.16.2
├── joi@11.3.4
├── morgan@1.9.0
├── nodemon@1.12.1
├── sequelize@4.13.10
└── sqlite3@3.1.8
```
**Error message:**
```
/home/chris_l/dev/tab-tracker/server/src/controllers/AuthenticationController.js:17
  async login (req, res) {
  ^^^^^

SyntaxError: Unexpected token async
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/chris_l/dev/tab-tracker/server/src/routes.js:1:96)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/chris_l/dev/tab-tracker/server/src/app.js:15:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by gaspoweredkiwi** [comment]
As with most issues, it turned out to be a typo... well done me.
